"""Static rule definitions for PE diligence analysis."""
from __future__ import annotations

import re
from typing import Dict, List

from app.verticals.private_equity.diligence.doc_types import (
    CONTRACTUAL_DOC_TYPES,
    FINANCIAL_DOC_TYPES,
    PEDocumentType,
    TRANSACTION_DOC_TYPES,
    validate_doc_type_list,
)

CHECKLIST_TEMPLATE = [
    {"item_key": "financial_statements", "title": "Financial Statements", "category": "financials", "priority": 1, "required": True},
    {"item_key": "customer_concentration", "title": "Customer Concentration", "category": "commercial", "priority": 1, "required": True},
    {"item_key": "debt_covenants", "title": "Debt & Covenant Package", "category": "legal_financial", "priority": 1, "required": True},
    {"item_key": "key_contracts", "title": "Key Contracts", "category": "legal", "priority": 2, "required": True},
    {"item_key": "regulatory_compliance", "title": "Regulatory Compliance", "category": "legal", "priority": 2, "required": True},
    {"item_key": "litigation_history", "title": "Litigation History", "category": "legal", "priority": 2, "required": True},
    {"item_key": "ip_assets", "title": "IP & Technology Assets", "category": "ip", "priority": 3, "required": False},
    {"item_key": "hr_roster", "title": "Leadership & HR Overview", "category": "people", "priority": 3, "required": False},
    {"item_key": "insurance_coverage", "title": "Insurance Coverage", "category": "legal", "priority": 3, "required": False},
    {"item_key": "tax_structure", "title": "Tax Structure", "category": "financials", "priority": 2, "required": False},
    {"item_key": "environmental", "title": "Environmental & Compliance", "category": "regulatory", "priority": 3, "required": False},
    {"item_key": "data_privacy", "title": "Data Privacy & Security", "category": "regulatory", "priority": 3, "required": False},
    {"item_key": "working_capital", "title": "Working Capital Analysis", "category": "financials", "priority": 1, "required": True},
    {"item_key": "spa_transaction_terms", "title": "SPA / Transaction Terms", "category": "legal", "priority": 1, "required": True},
    {"item_key": "related_party_transactions", "title": "Related Party Transactions", "category": "governance", "priority": 1, "required": True},
    {"item_key": "ebitda_quality", "title": "EBITDA Quality & Adjustments", "category": "financials", "priority": 2, "required": False},
    {"item_key": "management_incentive_plan", "title": "Management Incentive Plan & Equity Rollover", "category": "people", "priority": 2, "required": False},
    {"item_key": "vendor_supplier_concentration", "title": "Vendor / Supplier Concentration", "category": "commercial", "priority": 2, "required": False},
    {"item_key": "pension_benefits", "title": "Pension & Benefits Obligations", "category": "financials", "priority": 3, "required": False},
    {"item_key": "antitrust_approvals", "title": "Antitrust / Regulatory Approvals", "category": "regulatory", "priority": 3, "required": False},
]

CHECKLIST_RULES: Dict[str, dict] = {
    "financial_statements": {
        "clause_types": [],
        "numeric_metrics": ["revenue", "ebitda", "debt"],
        "doc_types": list(sorted(FINANCIAL_DOC_TYPES)),
        "keywords": [],
        "check_llm_financials": True,
        "base_confidence": 0.84,
        "partial_keywords": [],
    },
    "customer_concentration": {
        "clause_types": ["customer_contract", "revenue_share", "exclusivity", "mfn_pricing"],
        "numeric_metrics": [],
        "doc_types": [PEDocumentType.CUSTOMER_CONTRACT.value, PEDocumentType.OFFERING_MEMORANDUM.value],
        "keywords": ["customer concentration", "top customer", "top 10 customer", "key account", "concentration risk"],
        "check_llm_financials": False,
        "base_confidence": 0.80,
        "partial_keywords": ["customer", "client"],
    },
    "debt_covenants": {
        "clause_types": ["debt_covenant", "leverage_ratio", "interest_coverage", "event_of_default", "prepayment"],
        "numeric_metrics": [],
        "doc_types": [PEDocumentType.FINANCIAL_STATEMENT.value, PEDocumentType.QOE_REPORT.value, PEDocumentType.LEGAL_CONTRACT.value],
        "keywords": [],
        "check_llm_financials": False,
        "base_confidence": 0.82,
        "partial_keywords": [],
    },
    "key_contracts": {
        "clause_types": ["change_of_control", "assignment_consent", "termination_penalty", "termination", "customer_contract", "exclusivity", "representations_warranties"],
        "numeric_metrics": [],
        "doc_types": list(sorted(CONTRACTUAL_DOC_TYPES)),
        "keywords": [],
        "check_llm_financials": False,
        "base_confidence": 0.81,
        "partial_keywords": [],
    },
    "regulatory_compliance": {
        "clause_types": [],
        "numeric_metrics": [],
        "doc_types": [
            PEDocumentType.REGULATORY_FILING.value,
            PEDocumentType.POLICY_DOCUMENT.value,
            PEDocumentType.PURCHASE_AGREEMENT.value,
            PEDocumentType.MERGER_AGREEMENT.value,
            PEDocumentType.DISCLOSURE_SCHEDULE.value,
        ],
        "keywords": ["regulatory", "compliance", "regulated", "regulation", "permit", "licence", "license", "FDA", "SEC", "FINRA", "FCA"],
        "check_llm_financials": False,
        "base_confidence": 0.72,
        "partial_keywords": ["compliance"],
    },
    "litigation_history": {
        "clause_types": [],
        "numeric_metrics": [],
        "doc_types": [
            PEDocumentType.DISCLOSURE_SCHEDULE.value,
            PEDocumentType.REGULATORY_FILING.value,
            PEDocumentType.PURCHASE_AGREEMENT.value,
            PEDocumentType.MERGER_AGREEMENT.value,
            PEDocumentType.LEGAL_CONTRACT.value,
        ],
        "keywords": ["litigation", "lawsuit", "legal proceedings", "arbitration", "dispute", "claim", "alleged", "indictment"],
        "check_llm_financials": False,
        "base_confidence": 0.75,
        "partial_keywords": ["dispute", "claim"],
    },
    "litigation_disclosure": {
        "clause_types": [],
        "numeric_metrics": [],
        "doc_types": [],
        "keywords": ["litigation", "disclosure", "lawsuit", "pending", "threatened", "contingent liability"],
        "check_llm_financials": False,
        "base_confidence": 0.75,
        "partial_keywords": ["litigation", "disclosure"],
    },
    "ip_assets": {
        "clause_types": ["ip_assignment", "license_terms"],
        "numeric_metrics": [],
        "doc_types": [
            PEDocumentType.IP_LICENSE.value,
            PEDocumentType.EMPLOYMENT_AGREEMENT.value,
            PEDocumentType.PURCHASE_AGREEMENT.value,
            PEDocumentType.MERGER_AGREEMENT.value,
            PEDocumentType.DISCLOSURE_SCHEDULE.value,
        ],
        "keywords": ["patent", "trademark", "intellectual property", "proprietary technology", "trade secret", "copyright"],
        "check_llm_financials": False,
        "base_confidence": 0.72,
        "partial_keywords": ["intellectual", "patent", "trademark"],
    },
    "hr_roster": {
        "clause_types": ["employment_term", "severance", "equity_vesting"],
        "numeric_metrics": [],
        "doc_types": [
            PEDocumentType.EMPLOYMENT_AGREEMENT.value,
            PEDocumentType.SHAREHOLDER_AGREEMENT.value,
            PEDocumentType.CHARTER_DOCUMENT.value,
        ],
        "keywords": ["management team", "employee", "headcount", "key person", "key employee", "organization chart"],
        "check_llm_financials": False,
        "base_confidence": 0.70,
        "partial_keywords": ["employee", "management"],
    },
    "insurance_coverage": {
        "clause_types": [],
        "numeric_metrics": [],
        "doc_types": [
            PEDocumentType.INSURANCE_DOCUMENT.value,
            PEDocumentType.PURCHASE_AGREEMENT.value,
            PEDocumentType.DISCLOSURE_SCHEDULE.value,
        ],
        "keywords": ["insurance", "D&O", "directors and officers", "E&O", "liability coverage", "indemnification insurance", "general liability"],
        "check_llm_financials": False,
        "base_confidence": 0.70,
        "partial_keywords": ["insurance"],
    },
    "tax_structure": {
        "clause_types": [],
        "numeric_metrics": [],
        "doc_types": [
            PEDocumentType.TAX_DOCUMENT.value,
            PEDocumentType.PURCHASE_AGREEMENT.value,
            PEDocumentType.FINANCIAL_STATEMENT.value,
            PEDocumentType.DISCLOSURE_SCHEDULE.value,
        ],
        "keywords": ["tax structure", "transfer pricing", "net operating loss", "NOL", "tax jurisdiction", "tax liability", "deferred tax"],
        "check_llm_financials": False,
        "base_confidence": 0.70,
        "partial_keywords": ["tax"],
    },
    "environmental": {
        "clause_types": [],
        "numeric_metrics": [],
        "doc_types": [
            PEDocumentType.POLICY_DOCUMENT.value,
            PEDocumentType.REGULATORY_FILING.value,
            PEDocumentType.PURCHASE_AGREEMENT.value,
            PEDocumentType.DISCLOSURE_SCHEDULE.value,
        ],
        "keywords": ["environmental", "ESG", "emissions", "hazardous", "remediation", "climate", "carbon", "sustainability"],
        "check_llm_financials": False,
        "base_confidence": 0.68,
        "partial_keywords": ["environmental", "ESG"],
    },
    "data_privacy": {
        "clause_types": [],
        "numeric_metrics": [],
        "doc_types": [
            PEDocumentType.POLICY_DOCUMENT.value,
            PEDocumentType.REGULATORY_FILING.value,
            PEDocumentType.LEGAL_CONTRACT.value,
            PEDocumentType.DISCLOSURE_SCHEDULE.value,
            PEDocumentType.CUSTOMER_CONTRACT.value,
        ],
        "keywords": ["GDPR", "CCPA", "data privacy", "data protection", "cybersecurity", "SOC 2", "ISO 27001", "personal data"],
        "check_llm_financials": False,
        "base_confidence": 0.68,
        "partial_keywords": ["data privacy", "cybersecurity"],
    },
    "working_capital": {
        "clause_types": [],
        "numeric_metrics": ["working_capital", "current_ratio"],
        "doc_types": list(sorted(FINANCIAL_DOC_TYPES)),
        "keywords": ["working capital", "net working capital", "WC peg", "cash conversion cycle", "current assets", "current liabilities", "accounts receivable", "accounts payable"],
        "check_llm_financials": True,
        "base_confidence": 0.80,
        "partial_keywords": ["working capital"],
    },
    "spa_transaction_terms": {
        "clause_types": ["representations_warranties", "indemnification_cap", "purchase_price_mechanism", "earnout", "closing_condition", "mac_clause", "basket", "survival"],
        "numeric_metrics": [],
        "doc_types": list(TRANSACTION_DOC_TYPES),
        "keywords": ["purchase price", "closing conditions", "material adverse change", "representations and warranties", "indemnification"],
        "check_llm_financials": False,
        "base_confidence": 0.85,
        "partial_keywords": ["purchase agreement", "SPA"],
    },
    "related_party_transactions": {
        "clause_types": ["related_party_transaction"],
        "numeric_metrics": [],
        "doc_types": [
            PEDocumentType.SHAREHOLDER_AGREEMENT.value,
            PEDocumentType.CHARTER_DOCUMENT.value,
            PEDocumentType.FINANCIAL_STATEMENT.value,
            PEDocumentType.DISCLOSURE_SCHEDULE.value,
            PEDocumentType.REGULATORY_FILING.value,
        ],
        "keywords": ["related party", "related-party", "shareholder loan", "intercompany", "non-arm's length", "affiliate transaction", "management fee", "connected party"],
        "check_llm_financials": False,
        "base_confidence": 0.76,
        "partial_keywords": ["related party", "affiliate"],
    },
    "ebitda_quality": {
        "clause_types": [],
        "numeric_metrics": ["ebitda"],
        "doc_types": ["qoe_report"],
        "keywords": ["EBITDA adjustment", "add-back", "addback", "one-time item", "non-recurring", "normalized EBITDA", "quality of earnings", "pro forma", "run-rate"],
        "check_llm_financials": True,
        "base_confidence": 0.79,
        "partial_keywords": ["add-back", "normalized", "run-rate"],
    },
    "management_incentive_plan": {
        "clause_types": ["equity_vesting", "equity_option", "equity_rollover", "severance"],
        "numeric_metrics": [],
        "doc_types": [
            PEDocumentType.EMPLOYMENT_AGREEMENT.value,
            PEDocumentType.SHAREHOLDER_AGREEMENT.value,
            PEDocumentType.CHARTER_DOCUMENT.value,
        ],
        "keywords": ["management incentive", "equity rollover", "MIP", "rollover equity", "option pool", "phantom equity", "LTIP", "retention bonus", "sweet equity"],
        "check_llm_financials": False,
        "base_confidence": 0.73,
        "partial_keywords": ["equity rollover", "MIP"],
    },
    "vendor_supplier_concentration": {
        "clause_types": [],
        "numeric_metrics": [],
        "doc_types": [
            PEDocumentType.VENDOR_CONTRACT.value,
            PEDocumentType.PURCHASE_AGREEMENT.value,
            PEDocumentType.DISCLOSURE_SCHEDULE.value,
        ],
        "keywords": ["supplier concentration", "vendor concentration", "sole source", "single supplier", "key supplier", "critical vendor", "top supplier"],
        "check_llm_financials": False,
        "base_confidence": 0.72,
        "partial_keywords": ["supplier", "vendor concentration"],
    },
    "pension_benefits": {
        "clause_types": [],
        "numeric_metrics": [],
        "doc_types": [],
        "keywords": ["pension", "defined benefit", "OPEB", "retirement obligation", "actuarial liability", "pension deficit", "unfunded pension", "DB scheme"],
        "check_llm_financials": False,
        "base_confidence": 0.71,
        "partial_keywords": ["pension", "retirement obligation"],
    },
    "antitrust_approvals": {
        "clause_types": [],
        "numeric_metrics": [],
        "doc_types": [
            PEDocumentType.REGULATORY_FILING.value,
            PEDocumentType.PURCHASE_AGREEMENT.value,
            PEDocumentType.MERGER_AGREEMENT.value,
        ],
        "keywords": ["HSR", "antitrust", "merger control", "competition authority", "regulatory approval", "CFIUS", "Hart-Scott-Rodino", "merger clearance"],
        "check_llm_financials": False,
        "base_confidence": 0.74,
        "partial_keywords": ["antitrust", "merger control"],
    },
}

EXPECTED_CLAUSES_BY_DOC_TYPE: Dict[str, List[tuple]] = {
    "purchase_agreement": [
        ("representations_warranties", "Representations & Warranties", "high"),
        ("indemnification_cap", "Indemnification / Liability Cap", "high"),
        ("material_adverse_change", "Material Adverse Change (MAC) Clause", "high"),
        ("closing_conditions", "Conditions to Closing", "medium"),
        ("purchase_price_adjustment", "Purchase Price Adjustment Mechanism", "medium"),
    ],
    "merger_agreement": [
        ("representations_warranties", "Representations & Warranties", "high"),
        ("indemnification_cap", "Indemnification / Liability Cap", "high"),
        ("material_adverse_change", "Material Adverse Change (MAC) Clause", "high"),
        ("closing_conditions", "Conditions to Closing", "medium"),
        ("purchase_price_adjustment", "Purchase Price Adjustment Mechanism", "medium"),
    ],
    "customer_contract": [
        ("change_of_control", "Change of Control Provision", "medium"),
        ("termination", "Termination Rights", "medium"),
        ("exclusivity", "Exclusivity / Restrictive Commercial Terms", "low"),
    ],
    "vendor_contract": [
        ("change_of_control", "Change of Control Provision", "medium"),
        ("termination", "Termination Rights", "medium"),
    ],
    "employment_agreement": [
        ("severance", "Severance / Change-of-Control Compensation", "medium"),
        ("equity_vesting", "Equity Vesting / Acceleration", "medium"),
        ("non_compete", "Non-Compete / Restrictive Covenant", "low"),
    ],
    "ip_license": [
        ("license_terms", "License Scope & Restrictions", "high"),
        ("ip_assignment", "IP Assignment / Ownership", "high"),
    ],
    "shareholder_agreement": [
        ("drag_along", "Drag-Along Rights", "medium"),
        ("tag_along", "Tag-Along Rights", "medium"),
        ("change_of_control", "Change of Control / Transfer Restriction", "medium"),
    ],
    "legal_contract": [
        ("change_of_control", "Change of Control Provision", "medium"),
        ("termination", "Termination Rights", "medium"),
        ("assignment_consent", "Assignment Restrictions", "low"),
    ],
}

CLAUSE_DEFS: Dict[str, dict] = {
    "change_of_control": {
        "pattern": re.compile(r"\bchange[\s-]*of[\s-]*control\b", re.IGNORECASE),
        "category": "contract", "severity": "high", "confidence": 0.91,
        "title": "Change-of-control clause detected",
        "description": "A change-of-control clause was identified and should be reviewed for transfer restrictions.",
        "recommendation": "Review assignment/consent requirements with counsel.",
    },
    "assignment_consent": {
        "pattern": re.compile(r"\b(assign(?:ment)?|consent)\b.{0,90}\b(change[\s-]*of[\s-]*control|transfer)\b", re.IGNORECASE),
        "category": "contract", "severity": "medium", "confidence": 0.84,
        "title": "Assignment/consent language detected",
        "description": "Assignment or consent constraints may require third-party approvals.",
        "recommendation": "List contracts requiring counterpart consent and map to closing conditions.",
    },
    "novation": {
        "pattern": re.compile(r"\bnovation\b", re.IGNORECASE),
        "category": "contract", "severity": "medium", "confidence": 0.82,
        "title": "Novation clause detected",
        "description": "Novation language indicates a contract may be substituted or transferred to a new party.",
        "recommendation": "Confirm whether novation requires counterparty consent and assess timing risk.",
    },
    "drag_along": {
        "pattern": re.compile(r"\bdrag[\s-]*along\b", re.IGNORECASE),
        "category": "contract", "severity": "medium", "confidence": 0.88,
        "title": "Drag-along provision detected",
        "description": "Drag-along rights allow majority shareholders to compel minority shareholders to sell.",
        "recommendation": "Verify drag-along threshold, notice period, and price protections for minority.",
    },
    "tag_along": {
        "pattern": re.compile(r"\btag[\s-]*along\b", re.IGNORECASE),
        "category": "contract", "severity": "low", "confidence": 0.87,
        "title": "Tag-along provision detected",
        "description": "Tag-along rights allow minority shareholders to join a majority sale on the same terms.",
        "recommendation": "Confirm tag-along scope and whether it applies to this transaction structure.",
    },
    "customer_contract": {
        "pattern": re.compile(r"\b(master[\s-]*service[\s-]*agreement|MSA|customer[\s-]*agreement|supply[\s-]*agreement|service[\s-]*contract)\b", re.IGNORECASE),
        "category": "commercial", "severity": "medium", "confidence": 0.80,
        "title": "Key customer contract detected",
        "description": "A master service agreement or key customer contract was identified.",
        "recommendation": "Review renewal terms, termination rights, and change-of-control provisions in each contract.",
    },
    "revenue_share": {
        "pattern": re.compile(r"\brevenue[\s-]*shar(e|ing)\b", re.IGNORECASE),
        "category": "commercial", "severity": "medium", "confidence": 0.83,
        "title": "Revenue sharing arrangement detected",
        "description": "Revenue share provisions may affect net margin and post-close financial projections.",
        "recommendation": "Extract revenue share percentages and assess impact on pro-forma EBITDA.",
    },
    "exclusivity": {
        "pattern": re.compile(r"\b(exclusiv(e|ity)|sole[\s-]*source|exclusive[\s-]*supplier)\b", re.IGNORECASE),
        "category": "commercial", "severity": "high", "confidence": 0.85,
        "title": "Exclusivity / sole-source clause detected",
        "description": "Exclusivity provisions may restrict the ability to engage alternative suppliers or customers post-close.",
        "recommendation": "Map exclusivity scope and duration; assess impact on growth strategy.",
    },
    "mfn_pricing": {
        "pattern": re.compile(r"\b(most[\s-]*favou?red[\s-]*nation|MFN\b|best[\s-]*price[\s-]*guarantee)\b", re.IGNORECASE),
        "category": "commercial", "severity": "medium", "confidence": 0.84,
        "title": "Most Favoured Nation (MFN) pricing clause detected",
        "description": "MFN clauses require offering a counterparty the best pricing given to any other party.",
        "recommendation": "Identify MFN beneficiaries and assess margin compression risk at scale.",
    },
    "termination": {
        "pattern": re.compile(r"\btermination\b.{0,80}\b(for[\s-]*convenience|without[\s-]*cause|at[\s-]*will|upon[\s-]*notice)\b", re.IGNORECASE),
        "category": "commercial", "severity": "medium", "confidence": 0.80,
        "title": "Termination-for-convenience clause detected",
        "description": "Contract can be terminated at will or upon notice without cause.",
        "recommendation": "Quantify revenue at risk per contract and assess notice period adequacy.",
    },
    "termination_penalty": {
        "pattern": re.compile(r"\btermination\b.{0,90}\b(penalt(y|ies)|fee|liquidated damages)\b", re.IGNORECASE),
        "category": "legal", "severity": "high", "confidence": 0.88,
        "title": "Termination penalty language detected",
        "description": "Termination provisions may include penalty/fee exposure.",
        "recommendation": "Quantify termination penalty scenarios and trigger conditions.",
    },
    "debt_covenant": {
        "pattern": re.compile(r"\b(covenant|leverage ratio|debt service|interest coverage)\b", re.IGNORECASE),
        "category": "debt", "severity": "medium", "confidence": 0.80,
        "title": "Debt covenant language detected",
        "description": "Debt covenant references were found and may impact post-close flexibility.",
        "recommendation": "Extract covenant thresholds and test against current and projected financials.",
    },
    "leverage_ratio": {
        "pattern": re.compile(r"\b(leverage[\s-]*ratio|total[\s-]*net[\s-]*leverage|senior[\s-]*secured[\s-]*leverage|net[\s-]*leverage)\b", re.IGNORECASE),
        "category": "debt", "severity": "high", "confidence": 0.87,
        "title": "Leverage ratio covenant detected",
        "description": "A leverage ratio covenant restricts total debt relative to EBITDA.",
        "recommendation": "Extract the leverage threshold and test headroom under base, downside, and acquisition scenarios.",
    },
    "interest_coverage": {
        "pattern": re.compile(r"\b(interest[\s-]*coverage|fixed[\s-]*charge[\s-]*coverage|FCCR\b|DSCR\b)\b", re.IGNORECASE),
        "category": "debt", "severity": "medium", "confidence": 0.84,
        "title": "Interest coverage / FCCR covenant detected",
        "description": "An interest coverage or fixed charge coverage ratio covenant limits debt service capacity.",
        "recommendation": "Test covenant headroom under projected EBITDA and rising rate scenarios.",
    },
    "event_of_default": {
        "pattern": re.compile(r"\b(event[\s-]*of[\s-]*default|cross[\s-]*default|payment[\s-]*default)\b", re.IGNORECASE),
        "category": "debt", "severity": "high", "confidence": 0.89,
        "title": "Event of default provision detected",
        "description": "Events of default (including cross-default) can trigger acceleration of debt obligations.",
        "recommendation": "List all events of default and cross-default triggers; confirm no current breach.",
    },
    "prepayment": {
        "pattern": re.compile(r"\b(prepayment|prepay\b|make[\s-]*whole|call[\s-]*premium|early[\s-]*redemption|voluntary[\s-]*prepayment)\b", re.IGNORECASE),
        "category": "debt", "severity": "medium", "confidence": 0.82,
        "title": "Prepayment / call premium detected",
        "description": "Prepayment provisions may impose make-whole or call premium costs on early debt repayment.",
        "recommendation": "Quantify prepayment cost at expected hold period and refinancing scenarios.",
    },
    "ip_assignment": {
        "pattern": re.compile(r"\b(ip[\s-]*assignment|intellectual[\s-]*property[\s-]*assign|work[\s-]*for[\s-]*hire|work[\s-]*made[\s-]*for[\s-]*hire)\b", re.IGNORECASE),
        "category": "ip", "severity": "high", "confidence": 0.85,
        "title": "IP assignment clause detected",
        "description": "IP assignment provisions transfer ownership of intellectual property.",
        "recommendation": "Confirm direction of assignment (to company vs. from company) and scope of IP transferred.",
    },
    "license_terms": {
        "pattern": re.compile(r"\b(licens(e|or|ee|ing)|royalt(y|ies)|sublicens)\b", re.IGNORECASE),
        "category": "ip", "severity": "medium", "confidence": 0.78,
        "title": "License grant detected",
        "description": "License provisions grant rights to use intellectual property.",
        "recommendation": "Review exclusivity, sublicensing rights, and field-of-use restrictions.",
    },
    "non_compete": {
        "pattern": re.compile(r"\bnon[\s-]*compet(e|ition|itive)\b", re.IGNORECASE),
        "category": "ip", "severity": "medium", "confidence": 0.86,
        "title": "Non-compete restriction detected",
        "description": "Non-compete clauses restrict parties from competing for a defined period and geography.",
        "recommendation": "Assess enforceability, geographic scope, and duration relative to deal strategy.",
    },
    "non_solicit": {
        "pattern": re.compile(r"\bnon[\s-]*solicit(ation)?\b", re.IGNORECASE),
        "category": "ip", "severity": "low", "confidence": 0.85,
        "title": "Non-solicitation clause detected",
        "description": "Non-solicitation provisions restrict recruitment of employees or customers.",
        "recommendation": "Confirm scope (employees vs. customers), duration, and post-close applicability.",
    },
    "employment_term": {
        "pattern": re.compile(r"\b(employment[\s-]*agreement|employment[\s-]*contract|term[\s-]*of[\s-]*employment|at[\s-]*will[\s-]*employment)\b", re.IGNORECASE),
        "category": "people", "severity": "medium", "confidence": 0.82,
        "title": "Key employment agreement detected",
        "description": "An employment agreement for key personnel was identified.",
        "recommendation": "Confirm contract term, notice period, and retention/rollover plan for key employees.",
    },
    "severance": {
        "pattern": re.compile(r"\b(severance[\s-]*(pay|package|agreement)?|separation[\s-]*agreement|termination[\s-]*benefits)\b", re.IGNORECASE),
        "category": "people", "severity": "medium", "confidence": 0.84,
        "title": "Severance / separation provision detected",
        "description": "Severance terms define payout obligations upon termination of key employees.",
        "recommendation": "Quantify total severance exposure and assess change-of-control acceleration triggers.",
    },
    "equity_vesting": {
        "pattern": re.compile(r"\b(vest(ing|ed)\b|stock[\s-]*option|restricted[\s-]*stock|RSU\b|profits?[\s-]*interest|LTIP\b)\b", re.IGNORECASE),
        "category": "people", "severity": "medium", "confidence": 0.83,
        "title": "Equity vesting provision detected",
        "description": "Equity vesting terms affect management retention and dilution post-close.",
        "recommendation": "Map unvested equity by employee; assess acceleration on change of control.",
    },
    "representations_warranties": {
        "pattern": re.compile(r"\b(representations?[\s,]+warranties|reps?[\s,]+and[\s,]+warranties|R&W\b|representations?\s+set\s+forth)\b", re.IGNORECASE),
        "category": "spa", "severity": "high", "confidence": 0.88,
        "title": "Representations & Warranties detected",
        "description": "R&W provisions define seller's factual assertions about the business that form the basis of deal pricing.",
        "recommendation": "Review R&W scope, any qualifications (knowledge, materiality), and R&W insurance applicability.",
    },
    "indemnification_cap": {
        "pattern": re.compile(r"\bindemnif(y|ication|ied|ier)\b", re.IGNORECASE),
        "category": "spa", "severity": "high", "confidence": 0.90,
        "title": "Indemnification / liability provision detected",
        "description": "Indemnification provisions define remedies for R&W breaches; the cap limits total seller exposure.",
        "recommendation": "Extract indemnification cap, basket/deductible structure, and survival period for all rep categories.",
    },
    "material_adverse_change": {
        "pattern": re.compile(r"\b(material[\s-]*adverse[\s-]*(change|effect|event)|MAC\b|MAE\b|materially[\s-]*adverse)\b", re.IGNORECASE),
        "category": "spa", "severity": "high", "confidence": 0.87,
        "title": "Material Adverse Change (MAC/MAE) clause detected",
        "description": "MAC/MAE provisions allow a buyer to walk away if a materially adverse event occurs before closing.",
        "recommendation": "Review MAC definition, carve-outs (pandemic, market-wide events), and buyer walk-away conditions.",
    },
    "closing_conditions": {
        "pattern": re.compile(r"\b(condition(s)?[\s-]*to[\s-]*(closing|completion|consummation)|condition[\s-]*precedent|closing[\s-]*condition)\b", re.IGNORECASE),
        "category": "spa", "severity": "medium", "confidence": 0.85,
        "title": "Conditions to closing detected",
        "description": "Closing conditions must be satisfied before the transaction can complete.",
        "recommendation": "List all unsatisfied closing conditions and assess timing/regulatory risk to close.",
    },
    "purchase_price_adjustment": {
        "pattern": re.compile(r"\b(purchase[\s-]*price[\s-]*adjustment|working[\s-]*capital[\s-]*adjustment|true[\s-]*up|locked[\s-]*box|completion[\s-]*accounts)\b", re.IGNORECASE),
        "category": "spa", "severity": "medium", "confidence": 0.83,
        "title": "Purchase price adjustment mechanism detected",
        "description": "Price adjustment mechanics (working capital, locked box) affect final deal consideration.",
        "recommendation": "Confirm adjustment mechanism, reference date, and any disagreement resolution process.",
    },
    "earnout_mechanics": {
        "pattern": re.compile(r"\b(earn[\s-]*out|earnout|contingent[\s-]*consideration)\b", re.IGNORECASE),
        "category": "spa", "severity": "medium", "confidence": 0.86,
        "title": "Earnout provision detected",
        "description": "Earnout provisions tie a portion of deal consideration to future performance metrics.",
        "recommendation": "Extract earnout metric, period, cap, and any seller operating covenants during the earnout.",
    },
    "basket_deductible": {
        "pattern": re.compile(r"\b(basket\b|deductible\b|tipping[\s-]*basket|true[\s-]*deductible)\b.{0,60}\bindemnif\b", re.IGNORECASE),
        "category": "spa", "severity": "medium", "confidence": 0.80,
        "title": "Basket / deductible threshold detected",
        "description": "Indemnification basket/deductible sets a minimum loss threshold before claims can be made.",
        "recommendation": "Confirm basket type (tipping vs. true deductible), amount, and whether fundamental reps are excluded.",
    },
    "survival_period": {
        "pattern": re.compile(r"\b(survival[\s-]*(period|of[\s-]*representations?|clause)|representations?[\s-]*shall[\s-]*survive)\b", re.IGNORECASE),
        "category": "spa", "severity": "medium", "confidence": 0.82,
        "title": "Survival period for representations detected",
        "description": "Survival period determines how long after closing R&W claims can be brought.",
        "recommendation": "Note survival period by rep category (general reps vs. fundamental reps vs. tax reps).",
    },
    "litigation_disclosure": {
        "pattern": re.compile(r"\b(pending|threatened|litigation|lawsuit|claim|arbitration|proceeding|judicial|tribunal)\b", re.IGNORECASE),
        "category": "legal", "severity": "high", "confidence": 0.75,
        "title": "Litigation disclosure detected",
        "description": "Pending or threatened litigation, claims, or arbitration proceedings were identified.",
        "recommendation": "Obtain full schedule of litigation; assess materiality, likely outcomes, and indemnification coverage.",
    },
    "indemnity_obligation": {
        "pattern": re.compile(r"\b(indemnity[\s-]*obligation|indemnif(y|ied|ication)|hold[\s-]*harmless|duty[\s-]*to[\s-]*indemnif)\b", re.IGNORECASE),
        "category": "legal", "severity": "high", "confidence": 0.84,
        "title": "Indemnity obligation detected",
        "description": "Indemnity obligations require one party to compensate another for specified losses.",
        "recommendation": "Map indemnity obligations, caps, and triggers; confirm insurance coverage.",
    },
    "settlement_restriction": {
        "pattern": re.compile(r"\b(settlement[\s-]*(restriction|consent|approval|without[\s-]*consent))\b", re.IGNORECASE),
        "category": "legal", "severity": "medium", "confidence": 0.78,
        "title": "Settlement restriction clause detected",
        "description": "Settlement restriction provisions limit a party's ability to settle claims without consent.",
        "recommendation": "Identify which party controls settlement decisions and assess impact on litigation exposure.",
    },
    "contingent_liability": {
        "pattern": re.compile(r"\b(contingent[\s-]*liabilit|contingency[\s-]*reserve|potential[\s-]*liabilit|accrued[\s-]*liabilit|estimated[\s-]*loss)\b", re.IGNORECASE),
        "category": "legal", "severity": "high", "confidence": 0.80,
        "title": "Contingent liability disclosure detected",
        "description": "Contingent liabilities represent potential obligations dependent on future events.",
        "recommendation": "Obtain full schedule of contingent liabilities; stress-test balance sheet under adverse outcomes.",
    },
    "tax_representation": {
        "pattern": re.compile(r"\b(tax[\s-]*representation|tax[\s-]*warrant(y|ies)|tax[\s-]*rep\b|tax[\s-]*filing|tax[\s-]*return)\b", re.IGNORECASE),
        "category": "tax", "severity": "high", "confidence": 0.83,
        "title": "Tax representation / warranty detected",
        "description": "Tax representations and warranties define seller's assertions about tax compliance and filings.",
        "recommendation": "Review tax rep scope; confirm no open audits, disputes, or unfiled returns.",
    },
    "tax_indemnity": {
        "pattern": re.compile(r"\b(tax[\s-]*indemnit|tax[\s-]*gross[\s-]*up|pre[\s-]*closing[\s-]*tax|tax[\s-]*liabilit)\b", re.IGNORECASE),
        "category": "tax", "severity": "high", "confidence": 0.84,
        "title": "Tax indemnity / gross-up provision detected",
        "description": "Tax indemnity provisions allocate pre-closing tax liabilities between buyer and seller.",
        "recommendation": "Confirm pre-closing tax indemnity period, scope, and any gross-up obligations.",
    },
    "nol_carryforward": {
        "pattern": re.compile(r"\b(net[\s-]*operating[\s-]*loss|NOL\b|carryforward|carry[\s-]*forward|tax[\s-]*loss[\s-]*carry)\b", re.IGNORECASE),
        "category": "tax", "severity": "medium", "confidence": 0.80,
        "title": "NOL / tax loss carryforward detected",
        "description": "Net operating loss carryforwards represent future tax shield value.",
        "recommendation": "Quantify NOL balance, expiry schedule, and Section 382 limitation risk from change of control.",
    },
    "transfer_pricing": {
        "pattern": re.compile(r"\b(transfer[\s-]*pricing|arm'?s[\s-]*length|intercompany[\s-]*pricing|related[\s-]*party[\s-]*pric)\b", re.IGNORECASE),
        "category": "tax", "severity": "medium", "confidence": 0.79,
        "title": "Transfer pricing / arm's length provision detected",
        "description": "Transfer pricing provisions govern intercompany transaction pricing.",
        "recommendation": "Review transfer pricing documentation; assess exposure from non-arm's-length arrangements.",
    },
    "tax_step_up": {
        "pattern": re.compile(r"\b(tax[\s-]*step[\s-]*up|section[\s-]*338|338\(h\)\(10\)|basis[\s-]*step[\s-]*up|inside[\s-]*basis)\b", re.IGNORECASE),
        "category": "tax", "severity": "medium", "confidence": 0.82,
        "title": "Tax basis step-up / Section 338 election detected",
        "description": "Tax step-up provisions affect asset basis and future depreciation/amortization deductions.",
        "recommendation": "Model NPV of step-up benefit; confirm seller cooperation with 338(h)(10) if applicable.",
    },
    "supplier_concentration": {
        "pattern": re.compile(r"\b(sole[\s-]*source|single[\s-]*source|supplier[\s-]*concentration|key[\s-]*supplier|vendor[\s-]*concentration)\b", re.IGNORECASE),
        "category": "commercial", "severity": "high", "confidence": 0.83,
        "title": "Supplier concentration / sole-source risk detected",
        "description": "Significant reliance on a single supplier creates supply chain concentration risk.",
        "recommendation": "Identify top suppliers by spend; assess switching costs and availability of alternatives.",
    },
    "minimum_purchase_commitment": {
        "pattern": re.compile(r"\b(minimum[\s-]*purchase|minimum[\s-]*order|take[\s-]*or[\s-]*pay|volume[\s-]*commitment|minimum[\s-]*spend)\b", re.IGNORECASE),
        "category": "commercial", "severity": "medium", "confidence": 0.80,
        "title": "Minimum purchase / take-or-pay commitment detected",
        "description": "Minimum purchase or take-or-pay obligations create fixed cost exposure regardless of volume.",
        "recommendation": "Quantify minimum commitment amounts and assess penalty for shortfall.",
    },
    "price_escalation": {
        "pattern": re.compile(r"\b(price[\s-]*escalation|price[\s-]*adjustment|CPI[\s-]*escalat|annual[\s-]*price[\s-]*increas)\b", re.IGNORECASE),
        "category": "commercial", "severity": "medium", "confidence": 0.78,
        "title": "Price escalation / CPI adjustment clause detected",
        "description": "Price escalation provisions automatically increase contract prices over time.",
        "recommendation": "Model cost escalation impact on margins; assess ability to pass through increases.",
    },
    "regulatory_approval": {
        "pattern": re.compile(r"\b(regulatory[\s-]*approval|regulatory[\s-]*consent|regulatory[\s-]*clearance|antitrust[\s-]*approval|HSR\b|CFIUS\b)\b", re.IGNORECASE),
        "category": "regulatory", "severity": "high", "confidence": 0.87,
        "title": "Regulatory approval / antitrust clearance required",
        "description": "Closing is conditioned on obtaining regulatory or antitrust approval.",
        "recommendation": "Identify applicable filings (HSR, CFIUS, sector-specific); assess timeline and risk of conditions.",
    },
    "license_requirement": {
        "pattern": re.compile(r"\b(license[\s-]*requirement|permit[\s-]*required|authorization[\s-]*required|operating[\s-]*license)\b", re.IGNORECASE),
        "category": "regulatory", "severity": "medium", "confidence": 0.79,
        "title": "Operating license / permit requirement detected",
        "description": "Business operations require specific licenses, permits, or regulatory authorizations.",
        "recommendation": "Inventory all required licenses; confirm transferability and status post-close.",
    },
    "government_contract": {
        "pattern": re.compile(r"\b(government[\s-]*contract|federal[\s-]*contract|GSA[\s-]*schedule|FAR\b|DFARS\b|public[\s-]*sector[\s-]*agreement)\b", re.IGNORECASE),
        "category": "regulatory", "severity": "medium", "confidence": 0.82,
        "title": "Government / federal contract detected",
        "description": "Government contracts are subject to FAR/DFARS requirements and may restrict assignment.",
        "recommendation": "Review novation requirements, security clearance obligations, and termination-for-convenience clauses.",
    },
    "export_control": {
        "pattern": re.compile(r"\b(export[\s-]*control|ITAR\b|EAR\b|OFAC\b|export[\s-]*restriction|dual[\s-]*use)\b", re.IGNORECASE),
        "category": "regulatory", "severity": "high", "confidence": 0.85,
        "title": "Export control / sanctions restriction detected",
        "description": "Export control provisions (ITAR, EAR, OFAC) restrict the export of controlled goods, technology, or services.",
        "recommendation": "Assess ITAR/EAR classification of products; confirm no OFAC sanctions exposure; review foreign buyer restrictions.",
    },
    "data_processing_agreement": {
        "pattern": re.compile(r"\b(data[\s-]*processing[\s-]*agreement|DPA\b|data[\s-]*processor|personal[\s-]*data|data[\s-]*controller)\b", re.IGNORECASE),
        "category": "privacy", "severity": "medium", "confidence": 0.80,
        "title": "Data processing agreement (DPA) detected",
        "description": "DPAs govern the processing of personal data under GDPR and similar privacy frameworks.",
        "recommendation": "Review DPA terms; confirm post-close data processing authority and sub-processor obligations.",
    },
    "breach_notification": {
        "pattern": re.compile(r"\b(breach[\s-]*notification|security[\s-]*incident[\s-]*notice|data[\s-]*breach[\s-]*report)\b", re.IGNORECASE),
        "category": "privacy", "severity": "high", "confidence": 0.82,
        "title": "Data breach notification obligation detected",
        "description": "Breach notification provisions require timely reporting of data security incidents.",
        "recommendation": "Map notification timelines and recipients; confirm incident response plan is in place.",
    },
    "gdpr_compliance": {
        "pattern": re.compile(r"\b(GDPR\b|CCPA\b|CPRA\b|privacy[\s-]*regulation|data[\s-]*subject[\s-]*right|right[\s-]*to[\s-]*erasure)\b", re.IGNORECASE),
        "category": "privacy", "severity": "high", "confidence": 0.83,
        "title": "GDPR / CCPA compliance obligation detected",
        "description": "Privacy regulation references indicate obligations under GDPR, CCPA, or similar frameworks.",
        "recommendation": "Assess compliance posture; confirm data subject rights fulfilment and cross-border transfer mechanisms.",
    },
    "data_retention": {
        "pattern": re.compile(r"\b(data[\s-]*retention|retention[\s-]*period|retention[\s-]*schedule|data[\s-]*deletion[\s-]*policy)\b", re.IGNORECASE),
        "category": "privacy", "severity": "medium", "confidence": 0.78,
        "title": "Data retention / deletion policy detected",
        "description": "Data retention provisions specify how long personal or business data must be kept or deleted.",
        "recommendation": "Confirm retention schedules comply with applicable regulations and contractual obligations.",
    },
    "environmental_liability": {
        "pattern": re.compile(r"\b(environmental[\s-]*liabilit|contamination|hazardous[\s-]*material|CERCLA\b|Superfund|remediation[\s-]*cost)\b", re.IGNORECASE),
        "category": "esg", "severity": "high", "confidence": 0.84,
        "title": "Environmental liability / contamination risk detected",
        "description": "Environmental liability provisions address remediation obligations for contaminated sites.",
        "recommendation": "Obtain Phase I/II environmental assessments; quantify remediation cost estimates.",
    },
    "remediation_obligation": {
        "pattern": re.compile(r"\b(remediation[\s-]*obligation|clean[\s-]*up[\s-]*cost|environmental[\s-]*remediat|site[\s-]*cleanup)\b", re.IGNORECASE),
        "category": "esg", "severity": "high", "confidence": 0.82,
        "title": "Environmental remediation obligation detected",
        "description": "Remediation obligations require cleanup of environmental contamination at specified sites.",
        "recommendation": "Obtain remediation cost estimates; confirm insurance coverage and indemnification from seller.",
    },
    "esg_covenant": {
        "pattern": re.compile(r"\b(ESG[\s-]*covenant|sustainability[\s-]*covenant|social[\s-]*responsibility[\s-]*obligation)\b", re.IGNORECASE),
        "category": "esg", "severity": "medium", "confidence": 0.76,
        "title": "ESG / sustainability covenant detected",
        "description": "ESG covenants create ongoing obligations around environmental, social, or governance standards.",
        "recommendation": "Map ESG covenant requirements; assess compliance costs and reporting obligations.",
    },
    "carbon_commitment": {
        "pattern": re.compile(r"\b(carbon[\s-]*neutral|net[\s-]*zero|greenhouse[\s-]*gas[\s-]*target|emissions[\s-]*reduction|carbon[\s-]*offset)\b", re.IGNORECASE),
        "category": "esg", "severity": "medium", "confidence": 0.77,
        "title": "Carbon / net-zero commitment detected",
        "description": "Carbon neutrality or net-zero commitments create long-term emissions reduction obligations.",
        "recommendation": "Quantify cost of meeting carbon commitments; assess credibility of offset strategy.",
    },
    "rep_warranty_insurance": {
        "pattern": re.compile(r"\b(R&W[\s-]*insurance|rep[\s-]*and[\s-]*warranty[\s-]*insurance|representation[\s-]*warranty[\s-]*insurance)\b", re.IGNORECASE),
        "category": "insurance", "severity": "medium", "confidence": 0.85,
        "title": "R&W insurance policy detected",
        "description": "Representations & Warranties insurance shifts indemnification risk from seller to an insurer.",
        "recommendation": "Review policy limits, retention, exclusions, and underwriting scope relative to deal R&W.",
    },
    "tail_coverage": {
        "pattern": re.compile(r"\b(tail[\s-]*coverage|tail[\s-]*period|extended[\s-]*reporting[\s-]*period|run[\s-]*off[\s-]*coverage)\b", re.IGNORECASE),
        "category": "insurance", "severity": "medium", "confidence": 0.81,
        "title": "Tail / run-off insurance coverage detected",
        "description": "Tail coverage extends insurance protection for claims arising after policy expiration.",
        "recommendation": "Confirm tail period length, premium cost, and obligation to maintain (buyer vs. seller).",
    },
    "coverage_gap": {
        "pattern": re.compile(r"\b(coverage[\s-]*gap|uninsured[\s-]*risk|coverage[\s-]*exclusion|excluded[\s-]*from[\s-]*coverage)\b", re.IGNORECASE),
        "category": "insurance", "severity": "high", "confidence": 0.78,
        "title": "Insurance coverage gap / exclusion detected",
        "description": "Coverage gaps or exclusions indicate uninsured risks that may require alternative risk mitigation.",
        "recommendation": "Identify uninsured exposures; assess whether price adjustment or escrow is warranted.",
    },
    "exclusion_carveout": {
        "pattern": re.compile(r"\b(policy[\s-]*exclusion|coverage[\s-]*carve[\s-]*out|specific[\s-]*exclusion|excluded[\s-]*loss)\b", re.IGNORECASE),
        "category": "insurance", "severity": "medium", "confidence": 0.77,
        "title": "Policy exclusion / coverage carve-out detected",
        "description": "Policy exclusions or carve-outs limit coverage for specific risks or loss types.",
        "recommendation": "Map all exclusions against known risk exposures; confirm alternative coverage or reserve.",
    },
    "related_party_transaction": {
        "pattern": re.compile(r"\b(related[\s-]*party[\s-]*transaction|affiliate[\s-]*transaction|insider[\s-]*transaction)\b", re.IGNORECASE),
        "category": "governance", "severity": "high", "confidence": 0.85,
        "title": "Related party transaction detected",
        "description": "Transactions with related parties (affiliates, insiders) may not be on arm's-length terms.",
        "recommendation": "Obtain schedule of all related-party transactions; assess fairness and plan for unwinding post-close.",
    },
    "affiliate_payment": {
        "pattern": re.compile(r"\b(affiliate[\s-]*payment|intercompany[\s-]*payment|payment[\s-]*to[\s-]*affiliate)\b", re.IGNORECASE),
        "category": "governance", "severity": "medium", "confidence": 0.80,
        "title": "Affiliate / intercompany payment detected",
        "description": "Intercompany payments between affiliates may distort standalone financial performance.",
        "recommendation": "Normalise EBITDA for affiliate payments that will not continue post-close.",
    },
    "management_fee": {
        "pattern": re.compile(r"\b(management[\s-]*fee|monitoring[\s-]*fee|advisory[\s-]*fee[\s-]*to[\s-]*sponsor)\b", re.IGNORECASE),
        "category": "governance", "severity": "medium", "confidence": 0.82,
        "title": "Sponsor / management fee arrangement detected",
        "description": "Management or monitoring fees paid to a sponsor distort reported EBITDA.",
        "recommendation": "Add back management fees in EBITDA normalisation; confirm termination at close.",
    },
    "loan_to_officer": {
        "pattern": re.compile(r"\b(loan[\s-]*to[\s-]*officer|loan[\s-]*to[\s-]*director|shareholder[\s-]*loan|officer[\s-]*loan)\b", re.IGNORECASE),
        "category": "governance", "severity": "high", "confidence": 0.83,
        "title": "Loan to officer / director detected",
        "description": "Loans to officers or directors may violate Sarbanes-Oxley and create governance concerns.",
        "recommendation": "Require repayment before close; confirm SOX compliance and board approval.",
    },
    "working_capital_peg": {
        "pattern": re.compile(r"\b(working[\s-]*capital[\s-]*peg|working[\s-]*capital[\s-]*target|net[\s-]*working[\s-]*capital[\s-]*target|NWC[\s-]*peg)\b", re.IGNORECASE),
        "category": "financial", "severity": "medium", "confidence": 0.81,
        "title": "Working capital peg / NWC target detected",
        "description": "Working capital peg defines the target NWC level for price adjustment purposes.",
        "recommendation": "Agree on NWC definition (inclusions/exclusions) and peg methodology with seller.",
    },
    "revenue_recognition": {
        "pattern": re.compile(r"\b(revenue[\s-]*recognition|ASC[\s-]*606|IFRS[\s-]*15|percentage[\s-]*of[\s-]*completion)\b", re.IGNORECASE),
        "category": "financial", "severity": "medium", "confidence": 0.80,
        "title": "Revenue recognition policy reference detected",
        "description": "Revenue recognition references indicate adherence to ASC 606 / IFRS 15 or project-based accounting.",
        "recommendation": "Assess revenue recognition policies for conservatism; check for timing differences vs. cash collections.",
    },
    "deferred_revenue": {
        "pattern": re.compile(r"\b(deferred[\s-]*revenue|unearned[\s-]*revenue|contract[\s-]*liabilit|advance[\s-]*payment[\s-]*liabilit)\b", re.IGNORECASE),
        "category": "financial", "severity": "medium", "confidence": 0.80,
        "title": "Deferred revenue balance detected",
        "description": "Deferred revenue represents cash received before the related service or product is delivered.",
        "recommendation": "Assess deferred revenue burn-down schedule; include in NWC calculation and cash-free/debt-free adjustments.",
    },
    "normalized_ebitda": {
        "pattern": re.compile(r"\b(normalized[\s-]*EBITDA|adjusted[\s-]*EBITDA[\s-]*addback|pro[\s-]*forma[\s-]*adjustment|EBITDA[\s-]*bridge)\b", re.IGNORECASE),
        "category": "financial", "severity": "high", "confidence": 0.83,
        "title": "Normalized / adjusted EBITDA addback detected",
        "description": "EBITDA addbacks or pro-forma adjustments increase reported earnings; quality varies significantly.",
        "recommendation": "Scrutinise each addback for one-time nature, supportability, and buyer visibility.",
    },
    "voting_rights": {
        "pattern": re.compile(r"\b(voting[\s-]*right|voting[\s-]*power|supermajority[\s-]*vote|class[\s-]*[A-Z][\s-]*share|weighted[\s-]*vot)\b", re.IGNORECASE),
        "category": "governance", "severity": "medium", "confidence": 0.80,
        "title": "Voting rights / governance structure detected",
        "description": "Voting right provisions define control mechanics and approval thresholds.",
        "recommendation": "Map voting structure post-close; confirm buyer achieves required control for governance purposes.",
    },
    "board_composition": {
        "pattern": re.compile(r"\b(board[\s-]*seat|board[\s-]*composition|director[\s-]*appointment|board[\s-]*representation)\b", re.IGNORECASE),
        "category": "governance", "severity": "medium", "confidence": 0.81,
        "title": "Board composition / director appointment right detected",
        "description": "Board composition provisions define who appoints directors and may constrain buyer control.",
        "recommendation": "Confirm post-close board composition meets buyer governance requirements.",
    },
    "anti_dilution": {
        "pattern": re.compile(r"\b(anti[\s-]*dilution|weighted[\s-]*average[\s-]*anti|full[\s-]*ratchet|preemptive[\s-]*right|pro[\s-]*rata[\s-]*right)\b", re.IGNORECASE),
        "category": "governance", "severity": "medium", "confidence": 0.82,
        "title": "Anti-dilution / preemptive right detected",
        "description": "Anti-dilution provisions protect investors from ownership dilution in future financing rounds.",
        "recommendation": "Assess anti-dilution mechanics (weighted average vs. full ratchet); confirm waiver or termination at close.",
    },
    "liquidation_preference": {
        "pattern": re.compile(r"\b(liquidation[\s-]*preference|liquidation[\s-]*stack|participating[\s-]*preferred|waterfall[\s-]*distribution)\b", re.IGNORECASE),
        "category": "governance", "severity": "high", "confidence": 0.85,
        "title": "Liquidation preference / waterfall detected",
        "description": "Liquidation preferences define the distribution waterfall in a sale or liquidation scenario.",
        "recommendation": "Model waterfall distributions at various exit multiples; confirm preference amounts and participation rights.",
    },
}

CLAUSE_PATTERNS = {k: v["pattern"] for k, v in CLAUSE_DEFS.items() if v.get("pattern")}
CLAUSE_META = {k: {mk: mv for mk, mv in v.items() if mk != "pattern"} for k, v in CLAUSE_DEFS.items()}

METRIC_PATTERNS = {
    "revenue": re.compile(r"\b(revenue|sales)\b[^\n$]{0,80}\$?\s*([0-9]{1,3}(?:,[0-9]{3})*(?:\.\d+)?)(?:\s*(million|mm|m|billion|bn|b))?", re.IGNORECASE),
    "ebitda": re.compile(r"\b(adjusted\s+)?ebitda\b[^\n$]{0,80}\$?\s*([0-9]{1,3}(?:,[0-9]{3})*(?:\.\d+)?)(?:\s*(million|mm|m|billion|bn|b))?", re.IGNORECASE),
    "debt": re.compile(r"\b(debt|borrowings|loan balance)\b[^\n$]{0,80}\$?\s*([0-9]{1,3}(?:,[0-9]{3})*(?:\.\d+)?)(?:\s*(million|mm|m|billion|bn|b))?", re.IGNORECASE),
}

MULTIPLIERS = {
    None: 1.0,
    "m": 1_000_000.0,
    "mm": 1_000_000.0,
    "million": 1_000_000.0,
    "b": 1_000_000_000.0,
    "bn": 1_000_000_000.0,
    "billion": 1_000_000_000.0,
}


def _validate_checklist_rules() -> None:
    for item_key, rule in CHECKLIST_RULES.items():
        validate_doc_type_list(
            rule.get("doc_types"),
            context=f"checklist:{item_key}:doc_types",
        )


_validate_checklist_rules()
