"""Shared underwriting thresholds.

Keep analyst-tunable constants in one place so calculator, merger, and verdict
logic do not drift as the screening rules evolve.
"""

LINE_ITEMS_VS_RATIO_CUTOFF = 0.75
NOI_RECONCILIATION_GAP_PCT = 0.10
UNIT_MIX_GPR_MISMATCH_PCT = 0.05
ROLLOVER_CONCENTRATION_PCT = 0.40

EXPENSE_RATIO_LOW_PCT = 0.30
EXPENSE_RATIO_HIGH_PCT = 0.45
MARKET_SUPPLY_SQFT_PER_CAPITA_HIGH = 8.0
MARKET_SUPPLY_SQFT_PER_CAPITA_WATCH = 6.5
MARKET_SUPPLY_COMPETITOR_COUNT_WATCH = 8
MIXED_REVENUE_UNIT_SHARE_PCT = 0.20
MIXED_REVENUE_RENT_SHARE_PCT = 0.15

INCOME_PERIOD_FULL_YEAR_MONTHS = 12
INCOME_PERIOD_SHORT_BAND = range(6, 12)
INCOME_PERIOD_VERY_SHORT_THRESHOLD = 3

DSCR_YEAR_ONE_FLOOR = 1.25
STRESS_DSCR_FLOOR = 1.15
