/**
 * Extraction Result Export Utilities
 *
 * Exports CIM analysis results to professional Word documents
 * Includes ALL data sections (matching Excel export coverage)
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  Table,
  TableRow,
  TableCell,
  WidthType,
} from 'docx';

/**
 * Export extraction result as professional Word document
 * @param {Object} data - Extraction data (CIM analysis)
 * @param {Object} metadata - Extraction metadata
 */
export async function exportExtractionAsWord(data, metadata) {
  if (!data) {
    throw new Error('No data to export');
  }

  const companyName = data.company_info?.company_name || 'Company';
  const dateStr = new Date().toLocaleDateString();

  const children = [
    // Cover Page
    new Paragraph({
      text: 'Confidential Information Memorandum',
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),

    new Paragraph({
      text: companyName,
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
      spacing: { after: 300 },
    }),

    new Paragraph({
      children: [
        new TextRun({
          text: `Analysis Date: ${dateStr}`,
          bold: true,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),

    ...(metadata?.filename
      ? [
          new Paragraph({
            text: `Source: ${metadata.filename}`,
            alignment: AlignmentType.CENTER,
            spacing: { after: 300 },
          }),
        ]
      : []),

    // Divider
    new Paragraph({
      border: {
        bottom: {
          color: 'CCCCCC',
          space: 1,
          style: BorderStyle.SINGLE,
          size: 12,
        },
      },
      spacing: { after: 400 },
    }),
  ];

  // Process all sections dynamically
  addAllSections(children, data);

  // Footer
  children.push(
    new Paragraph({
      border: {
        top: {
          color: 'CCCCCC',
          space: 1,
          style: BorderStyle.SINGLE,
          size: 6,
        },
      },
      spacing: { before: 400, after: 200 },
    }),

    new Paragraph({
      children: [
        new TextRun({
          text: 'Generated by Sand Cloud Document Intelligence',
          italics: true,
          size: 18,
          color: '6B7280',
        }),
      ],
      alignment: AlignmentType.CENTER,
    })
  );

  // Add metadata if available
  if (metadata?.processing_time_ms) {
    children.push(
      new Paragraph({
        text: `Processing Time: ${metadata.processing_time_ms}ms`,
        alignment: AlignmentType.CENTER,
        spacing: { after: 50 },
      })
    );
  }

  // Create document
  const doc = new Document({
    sections: [
      {
        properties: {},
        children,
      },
    ],
  });

  // Generate and download
  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = sanitizeFilename(`${companyName}_CIM_Analysis.docx`);
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Dynamically add all sections from the data
 */
function addAllSections(children, data) {
  // Define section order and titles
  const sectionConfig = [
    { key: 'executive_summary', title: 'Executive Summary', type: 'text' },
    { key: 'company_info', title: 'Company Overview', type: 'object' },
    { key: 'financial_highlights', title: 'Financial Highlights', type: 'object' },
    { key: 'financial_performance', title: 'Financial Performance', type: 'object' },
    { key: 'balance_sheet', title: 'Balance Sheet', type: 'object' },
    { key: 'financial_ratios', title: 'Financial Ratios', type: 'object' },
    { key: 'valuation_multiples', title: 'Valuation Multiples', type: 'object' },
    { key: 'capital_structure', title: 'Capital Structure', type: 'object' },
    { key: 'operating_metrics', title: 'Operating Metrics', type: 'object' },
    { key: 'customer_market_analysis', title: 'Customer & Market Analysis', type: 'object' },
    { key: 'market_analysis', title: 'Market Analysis', type: 'object' },
    { key: 'investment_highlights', title: 'Investment Highlights', type: 'array' },
    { key: 'red_flags', title: 'Red Flags', type: 'array' },
    { key: 'risks', title: 'Risk Analysis', type: 'array' },
    { key: 'strategic_rationale', title: 'Strategic Rationale', type: 'object' },
    { key: 'investment_memo', title: 'Investment Memo', type: 'object' },
    { key: 'management_team', title: 'Management Team', type: 'array' },
  ];

  // Process each section
  for (const config of sectionConfig) {
    const sectionData = data[config.key];
    if (!sectionData) continue;

    // Add section heading
    children.push(
      new Paragraph({
        text: config.title,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 300, after: 200 },
      })
    );

    // Add content based on type
    if (config.type === 'text') {
      addTextContent(children, sectionData);
    } else if (config.type === 'array') {
      addArrayContent(children, sectionData, config.key);
    } else if (config.type === 'object') {
      addObjectContent(children, sectionData, config.key);
    }

    // Add spacing after section
    children.push(
      new Paragraph({
        spacing: { after: 300 },
      })
    );
  }
}

/**
 * Add text content (like executive summary)
 */
function addTextContent(children, text) {
  if (typeof text === 'string') {
    const paragraphs = text.split('\n\n');
    paragraphs.forEach((para) => {
      if (para.trim()) {
        children.push(
          new Paragraph({
            text: para.trim(),
            spacing: { after: 150 },
          })
        );
      }
    });
  }
}

/**
 * Add array content (like investment highlights, red flags)
 */
function addArrayContent(children, arr, key) {
  if (!Array.isArray(arr) || arr.length === 0) return;

  if (key === 'red_flags' || key === 'risks') {
    // Red flags with warning symbol
    arr.forEach((item) => {
      const text = typeof item === 'object' ? (item.flag || item.risk || item.description) : item;
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `⚠️ ${text}`,
              color: 'DC2626',
            }),
          ],
          spacing: { after: 100 },
        })
      );
    });
  } else if (key === 'management_team') {
    // Management team with detailed info
    arr.forEach((member) => {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: member.name || 'N/A',
              bold: true,
              size: 24,
            }),
            new TextRun({
              text: ` - ${member.title || 'N/A'}`,
              size: 24,
            }),
          ],
          spacing: { after: 50 },
        })
      );
      if (member.background) {
        children.push(
          new Paragraph({
            text: member.background,
            spacing: { after: 150 },
          })
        );
      }
    });
  } else {
    // Generic array items (investment highlights, etc.)
    arr.forEach((item, index) => {
      const text = typeof item === 'object' ? (item.highlight || item.text || item.description || JSON.stringify(item)) : item;
      children.push(
        new Paragraph({
          text: `${index + 1}. ${text}`,
          spacing: { after: 100 },
          bullet: { level: 0 },
        })
      );
    });
  }
}

/**
 * Add object content (like company info, financial data)
 */
function addObjectContent(children, obj, key) {
  if (!obj || typeof obj !== 'object') return;

  // Get all key-value pairs
  const pairs = Object.entries(obj)
    .filter(([_, value]) => value !== null && value !== undefined && value !== '')
    .map(([key, value]) => ({
      key: formatKeyName(key),
      value: formatValue(value),
    }));

  if (pairs.length === 0) return;

  // Add as key-value paragraphs
  pairs.forEach((pair) => {
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `${pair.key}: `,
            bold: true,
          }),
          new TextRun({
            text: String(pair.value),
          }),
        ],
        spacing: { after: 100 },
      })
    );
  });
}

/**
 * Format key name for display
 */
function formatKeyName(key) {
  return key
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (l) => l.toUpperCase());
}

/**
 * Format value for display
 */
function formatValue(value) {
  if (value === null || value === undefined) return '-';
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  if (typeof value === 'object' && !Array.isArray(value)) {
    // Nested object - format as JSON
    return JSON.stringify(value, null, 2);
  }
  if (Array.isArray(value)) {
    // Array - join with commas
    return value.join(', ');
  }
  return String(value);
}

/**
 * Sanitize filename for safe download
 */
function sanitizeFilename(filename) {
  return filename
    .replace(/[^a-z0-9.-]/gi, '_')
    .replace(/_+/g, '_')
    .substring(0, 50)
    .toLowerCase();
}
