"""add deleted_at to usage_logs

Revision ID: 050d731f2edf
Revises: 54e9e91d041f
Create Date: 2025-11-21 18:03:36.677819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '050d731f2edf'
down_revision = '54e9e91d041f'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('document_chunks', sa.Column('narrative_text', sa.Text(), nullable=True))
    # op.add_column('document_chunks', sa.Column('tables', sa.Text(), nullable=True))
    op.alter_column('extractions', 'artifact',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # op.add_column('usage_logs', sa.Column('filename', sa.String(length=255), nullable=True))
    op.add_column('usage_logs', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('usage_logs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('usage_logs', 'extraction_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint(op.f('usage_logs_extraction_id_fkey1'), 'usage_logs', type_='foreignkey')
    op.create_foreign_key(None, 'usage_logs', 'extractions', ['extraction_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usage_logs', type_='foreignkey')
    op.create_foreign_key(op.f('usage_logs_extraction_id_fkey1'), 'usage_logs', 'extractions', ['extraction_id'], ['id'])
    op.alter_column('usage_logs', 'extraction_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('usage_logs', 'deleted_at')
    op.drop_column('usage_logs', 'is_deleted')
    # op.drop_column('usage_logs', 'filename')
    op.alter_column('extractions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'processing'::character varying"),
               existing_nullable=False)
    # op.drop_column('document_chunks', 'tables')
    # op.drop_column('document_chunks', 'narrative_text')
    # ### end Alembic commands ###