"""add_chat_tables

Revision ID: 3d930caadeda
Revises: a5105e8fab5d
Create Date: 2025-11-10 04:28:22.310872

Note: This migration creates an HNSW index CONCURRENTLY to avoid blocking writes.
CONCURRENTLY requires special handling - see upgrade() function for details.
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '3d930caadeda'
down_revision = 'a5105e8fab5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Create chat tables and indexes.

    IMPORTANT: The HNSW index uses postgresql_concurrently=True to prevent blocking
    writes on production systems. This requires:

    1. Running outside a transaction (Alembic handles this with proper configuration)
    2. More time to build (but allows concurrent writes/reads)
    3. Two table scans instead of one (overhead is worth the concurrency)

    Without CONCURRENTLY: Index creation locks the table, blocking all writes
    With CONCURRENTLY: Index creation allows concurrent operations

    For large tables (millions of vectors), this can be the difference between
    seconds of downtime vs. zero downtime.
    """
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_collection_id'), 'chat_sessions', ['collection_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('collection_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('extraction_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_documents_collection_id'), 'collection_documents', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_documents_content_hash'), 'collection_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_collection_documents_extraction_id'), 'collection_documents', ['extraction_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_index', sa.Integer(), nullable=False),
    sa.Column('source_chunks', sa.Text(), nullable=True),
    sa.Column('retrieval_query', sa.Text(), nullable=True),
    sa.Column('num_chunks_retrieved', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_messages_session_id_index', 'chat_messages', ['session_id', 'message_index'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(384), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_type', sa.String(length=50), nullable=True),
    sa.Column('section_heading', sa.Text(), nullable=True),
    sa.Column('is_tabular', sa.Boolean(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['collection_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    # Create HNSW index concurrently to avoid blocking writes on large tables
    # CONCURRENTLY cannot run inside a transaction block, so this must be committed separately
    op.create_index(
        'idx_document_chunks_embedding',
        'document_chunks',
        ['embedding'],
        unique=False,
        postgresql_using='hnsw',
        postgresql_ops={'embedding': 'vector_cosine_ops'},
        postgresql_concurrently=True
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Drop chat tables and indexes.

    Note: Index drops with CONCURRENTLY also prevent blocking, though they're
    generally faster than creation.
    """
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    # Drop HNSW index concurrently to avoid blocking
    op.drop_index(
        'idx_document_chunks_embedding',
        table_name='document_chunks',
        postgresql_using='hnsw',
        postgresql_ops={'embedding': 'vector_cosine_ops'},
        postgresql_concurrently=True
    )
    op.drop_index('idx_document_chunks_document_id', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index('idx_chat_messages_session_id_index', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_collection_documents_extraction_id'), table_name='collection_documents')
    op.drop_index(op.f('ix_collection_documents_content_hash'), table_name='collection_documents')
    op.drop_index(op.f('ix_collection_documents_collection_id'), table_name='collection_documents')
    op.drop_table('collection_documents')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_collection_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###