"""add snapshot columns to extractions

Revision ID: 54e9e91d041f
Revises: 13f938167bfc
Create Date: 2025-11-20 03:25:03.458154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54e9e91d041f'
down_revision = '13f938167bfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Keep status column type intact (don't drop default)
    op.alter_column('extractions', 'status',
                    existing_type=sa.VARCHAR(length=20),
                    existing_nullable=False)
    op.create_foreign_key(None, 'usage_logs', 'extractions', ['extraction_id'], ['id'])

    # JSONB columns (no conversion to JSON)
    op.alter_column('workflow_runs', 'document_ids',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('workflow_runs', 'variables',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('workflow_runs', 'mode',
                    existing_type=sa.VARCHAR(length=30),
                    existing_nullable=False)
    op.alter_column('workflow_runs', 'status',
                    existing_type=sa.VARCHAR(length=20),
                    existing_nullable=False)
    op.alter_column('workflow_runs', 'artifact',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('workflow_runs', 'validation_errors',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('workflow_runs', 'context_stats',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('workflow_runs', 'version',
                    existing_type=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('workflows', 'variables_schema',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('workflows', 'output_schema',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('workflows', 'output_format',
                    existing_type=sa.VARCHAR(length=50),
                    existing_nullable=False)
    op.alter_column('workflows', 'min_documents',
                    existing_type=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('workflows', 'version',
                    existing_type=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('workflows', 'active',
                    existing_type=sa.BOOLEAN(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'active',
                    existing_type=sa.BOOLEAN(),
                    existing_nullable=False)
    op.alter_column('workflows', 'version',
                    existing_type=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('workflows', 'min_documents',
                    existing_type=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('workflows', 'output_format',
                    existing_type=sa.VARCHAR(length=50),
                    existing_nullable=False)
    op.alter_column('workflows', 'output_schema',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('workflows', 'variables_schema',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('workflow_runs', 'version',
                    existing_type=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('workflow_runs', 'context_stats',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('workflow_runs', 'validation_errors',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('workflow_runs', 'artifact',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('workflow_runs', 'status',
                    existing_type=sa.VARCHAR(length=20),
                    existing_nullable=False)
    op.alter_column('workflow_runs', 'mode',
                    existing_type=sa.VARCHAR(length=30),
                    existing_nullable=False)
    op.alter_column('workflow_runs', 'variables',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.alter_column('workflow_runs', 'document_ids',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True)
    op.drop_constraint(None, 'usage_logs', type_='foreignkey')
    # ### end Alembic commands ###
