"""add file_path to collection_documents

Revision ID: 7710583860d9
Revises: e26f80b0d932
Create Date: 2025-11-11 06:09:14.240506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7710583860d9'
down_revision = 'e26f80b0d932'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_documents', sa.Column('file_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_documents', 'file_path')
    # ### end Alembic commands ###