"""Add template tables and update JobState

Revision ID: 858eab2f9ffe
Revises: 8af61ecfd7fa
Create Date: 2025-12-21 16:16:07.017557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '858eab2f9ffe'
down_revision = '8af61ecfd7fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excel_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('schema_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excel_templates_active'), 'excel_templates', ['active'], unique=False)
    op.create_index(op.f('ix_excel_templates_category'), 'excel_templates', ['category'], unique=False)
    op.create_index(op.f('ix_excel_templates_user_id'), 'excel_templates', ['user_id'], unique=False)
    op.create_table('template_fill_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('template_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('field_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('field_detection_completed', sa.Boolean(), nullable=True),
    sa.Column('auto_mapping_completed', sa.Boolean(), nullable=True),
    sa.Column('user_review_completed', sa.Boolean(), nullable=True),
    sa.Column('extraction_completed', sa.Boolean(), nullable=True),
    sa.Column('filling_completed', sa.Boolean(), nullable=True),
    sa.Column('total_fields_detected', sa.Integer(), nullable=True),
    sa.Column('total_fields_mapped', sa.Integer(), nullable=True),
    sa.Column('total_fields_filled', sa.Integer(), nullable=True),
    sa.Column('auto_mapped_count', sa.Integer(), nullable=True),
    sa.Column('user_edited_count', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_stage', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['excel_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_fill_runs_status'), 'template_fill_runs', ['status'], unique=False)
    op.create_index(op.f('ix_template_fill_runs_user_id'), 'template_fill_runs', ['user_id'], unique=False)
    op.drop_constraint(op.f('cache_entries_content_hash_key'), 'cache_entries', type_='unique')
    op.drop_index(op.f('idx_cache_entries_content_hash'), table_name='cache_entries')
    op.create_index(op.f('ix_cache_entries_content_hash'), 'cache_entries', ['content_hash'], unique=True)
    op.drop_index(op.f('idx_collections_user_id'), table_name='collections')
    op.drop_index(op.f('idx_extractions_content_hash'), table_name='extractions')
    op.create_index(op.f('ix_extractions_content_hash'), 'extractions', ['content_hash'], unique=False)
    op.add_column('job_states', sa.Column('template_fill_run_id', sa.String(length=36), nullable=True))
    op.add_column('job_states', sa.Column('field_detection_completed', sa.Boolean(), nullable=True))
    op.add_column('job_states', sa.Column('auto_mapping_completed', sa.Boolean(), nullable=True))
    op.add_column('job_states', sa.Column('data_extraction_completed', sa.Boolean(), nullable=True))
    op.add_column('job_states', sa.Column('excel_filling_completed', sa.Boolean(), nullable=True))
    op.create_index('idx_job_states_template_fill_run_id', 'job_states', ['template_fill_run_id'], unique=False)
    op.create_foreign_key(None, 'job_states', 'template_fill_runs', ['template_fill_run_id'], ['id'], ondelete='CASCADE')

    # Update CHECK constraint to include template_fill_run_id
    op.drop_constraint('job_states_entity_exactly_one_fk_check', 'job_states', type_='check')
    op.create_check_constraint(
        'job_states_entity_exactly_one_fk_check',
        'job_states',
        '((extraction_id IS NOT NULL AND document_id IS NULL AND workflow_run_id IS NULL AND template_fill_run_id IS NULL) OR '
        '(extraction_id IS NULL AND document_id IS NOT NULL AND workflow_run_id IS NULL AND template_fill_run_id IS NULL) OR '
        '(extraction_id IS NULL AND document_id IS NULL AND workflow_run_id IS NOT NULL AND template_fill_run_id IS NULL) OR '
        '(extraction_id IS NULL AND document_id IS NULL AND workflow_run_id IS NULL AND template_fill_run_id IS NOT NULL))'
    )
    op.add_column('usage_logs', sa.Column('filename', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'usage_logs', 'extractions', ['extraction_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'vertical',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_users_vertical'), table_name='users')
    op.create_index(op.f('ix_users_vertical'), 'users', ['vertical'], unique=False)
    op.alter_column('workflow_runs', 'workflow_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_runs', 'workflow_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_index(op.f('ix_users_vertical'), table_name='users')
    op.create_index(op.f('idx_users_vertical'), 'users', ['vertical'], unique=False)
    op.alter_column('users', 'vertical',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'private_equity'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'usage_logs', type_='foreignkey')
    op.drop_column('usage_logs', 'filename')

    # Restore original CHECK constraint (without template_fill_run_id)
    op.drop_constraint('job_states_entity_exactly_one_fk_check', 'job_states', type_='check')
    op.create_check_constraint(
        'job_states_entity_exactly_one_fk_check',
        'job_states',
        '((extraction_id IS NOT NULL AND document_id IS NULL AND workflow_run_id IS NULL) OR '
        '(extraction_id IS NULL AND document_id IS NOT NULL AND workflow_run_id IS NULL) OR '
        '(extraction_id IS NULL AND document_id IS NULL AND workflow_run_id IS NOT NULL))'
    )

    op.drop_constraint(None, 'job_states', type_='foreignkey')
    op.drop_index('idx_job_states_template_fill_run_id', table_name='job_states')
    op.drop_column('job_states', 'excel_filling_completed')
    op.drop_column('job_states', 'data_extraction_completed')
    op.drop_column('job_states', 'auto_mapping_completed')
    op.drop_column('job_states', 'field_detection_completed')
    op.drop_column('job_states', 'template_fill_run_id')
    op.drop_index(op.f('ix_extractions_content_hash'), table_name='extractions')
    op.create_index(op.f('idx_extractions_content_hash'), 'extractions', ['content_hash'], unique=False)
    op.create_index(op.f('idx_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.drop_index(op.f('ix_cache_entries_content_hash'), table_name='cache_entries')
    op.create_index(op.f('idx_cache_entries_content_hash'), 'cache_entries', ['content_hash'], unique=False)
    op.create_unique_constraint(op.f('cache_entries_content_hash_key'), 'cache_entries', ['content_hash'])
    op.drop_index(op.f('ix_template_fill_runs_user_id'), table_name='template_fill_runs')
    op.drop_index(op.f('ix_template_fill_runs_status'), table_name='template_fill_runs')
    op.drop_table('template_fill_runs')
    op.drop_index(op.f('ix_excel_templates_user_id'), table_name='excel_templates')
    op.drop_index(op.f('ix_excel_templates_category'), table_name='excel_templates')
    op.drop_index(op.f('ix_excel_templates_active'), table_name='excel_templates')
    op.drop_table('excel_templates')
    # ### end Alembic commands ###