"""add_comparison_metadata_to_chat_messages

Revision ID: 8e390cb53d9a
Revises: ac7786162854
Create Date: 2026-01-30 01:23:15.161828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e390cb53d9a'
down_revision = 'ac7786162854'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('comparison_metadata', sa.Text(), nullable=True))
    op.alter_column('excel_templates', 'file_extension',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('excel_templates', 'file_extension',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'.xlsx'::character varying"),
               existing_nullable=False)
    op.drop_column('chat_messages', 'comparison_metadata')
    # ### end Alembic commands ###