"""Initial migration

Revision ID: a5105e8fab5d
Revises: None
Create Date: 2025-11-07 18:04:11.430860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5105e8fab5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cache_entries_content_hash'), 'cache_entries', ['content_hash'], unique=True)
    op.create_table('extractions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('user_tier', sa.String(length=20), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('pdf_type', sa.String(length=20), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('parser_used', sa.String(length=50), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('from_cache', sa.Boolean(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_content_hash'), 'extractions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_extractions_user_id'), 'extractions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('total_pages_processed', sa.Integer(), nullable=True),
    sa.Column('pages_this_month', sa.Integer(), nullable=True),
    sa.Column('pages_limit', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('billing_period_start', sa.DateTime(), nullable=True),
    sa.Column('billing_period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('job_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('extraction_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('parsing_completed', sa.Boolean(), nullable=True),
    sa.Column('chunking_completed', sa.Boolean(), nullable=True),
    sa.Column('summarizing_completed', sa.Boolean(), nullable=True),
    sa.Column('extracting_completed', sa.Boolean(), nullable=True),
    sa.Column('parsed_output_path', sa.String(length=500), nullable=True),
    sa.Column('chunks_path', sa.String(length=500), nullable=True),
    sa.Column('summaries_path', sa.String(length=500), nullable=True),
    sa.Column('combined_context_path', sa.String(length=500), nullable=True),
    sa.Column('error_stage', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('is_retryable', sa.Boolean(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_states_extraction_id'), 'job_states', ['extraction_id'], unique=False)
    op.create_table('parser_outputs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('extraction_id', sa.String(length=36), nullable=False),
    sa.Column('parser_name', sa.String(length=50), nullable=False),
    sa.Column('parser_version', sa.String(length=20), nullable=True),
    sa.Column('pdf_type', sa.String(length=20), nullable=True),
    sa.Column('raw_output', sa.JSON(), nullable=True),
    sa.Column('raw_output_length', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('extraction_id', sa.String(length=36), nullable=False),
    sa.Column('pages_processed', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_logs_user_id'), 'usage_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_logs_user_id'), table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_table('parser_outputs')
    op.drop_index(op.f('ix_job_states_extraction_id'), table_name='job_states')
    op.drop_table('job_states')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_extractions_user_id'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_content_hash'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_cache_entries_content_hash'), table_name='cache_entries')
    op.drop_table('cache_entries')
    # ### end Alembic commands ###