"""add_file_extension_to_excel_templates

Revision ID: ac7786162854
Revises: 858eab2f9ffe
Create Date: 2026-01-14 01:03:17.840711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7786162854'
down_revision = '858eab2f9ffe'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    # Add file_extension column with default value for existing rows
    op.add_column('excel_templates', sa.Column('file_extension', sa.String(length=10), nullable=False, server_default='.xlsx'))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('excel_templates', 'file_extension')
    # ### end Alembic commands ###