"""add collection_document_id to job_states for chat mode support

Revision ID: e26f80b0d932
Revises: 3d930caadeda
Create Date: 2025-11-10 22:17:41.127523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e26f80b0d932'
down_revision = '3d930caadeda'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_states', sa.Column('collection_document_id', sa.String(length=36), nullable=True))
    op.alter_column('job_states', 'extraction_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_job_states_collection_document_id'), 'job_states', ['collection_document_id'], unique=False)
    op.create_foreign_key(None, 'job_states', 'collection_documents', ['collection_document_id'], ['id'], ondelete='CASCADE')

    # Add CHECK constraint to ensure exactly one foreign key is set (manually added)
    op.create_check_constraint(
        'job_states_entity_xor_check',
        'job_states',
        '(extraction_id IS NOT NULL AND collection_document_id IS NULL) OR '
        '(extraction_id IS NULL AND collection_document_id IS NOT NULL)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    # Drop CHECK constraint first (manually added)
    op.drop_constraint('job_states_entity_xor_check', 'job_states', type_='check')

    op.drop_constraint(None, 'job_states', type_='foreignkey')
    op.drop_index(op.f('ix_job_states_collection_document_id'), table_name='job_states')
    op.alter_column('job_states', 'extraction_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('job_states', 'collection_document_id')
    # ### end Alembic commands ###